# Generated by Django 5.0.2 on 2024-02-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nolink', max_length=200, verbose_name='Nazwa')),
                ('link', models.CharField(default='nolink', max_length=200, verbose_name='Link')),
                ('target_price', models.FloatField(default=0.0, verbose_name='Cena docelowa')),
                ('current_price', models.FloatField(default=0.0, verbose_name='Cena obecna')),
                ('img', models.ImageField(default='images/default.jpg', upload_to='images/', verbose_name='Zdjęcie')),
            ],
            options={
                'verbose_name': 'Przedmiot',
                'verbose_name_plural': 'Przedmioty',
            },
        ),
    ]
