# Generated by Django 5.0.2 on 2024-02-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xkom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Aktywne'), (1, 'Nieaktywne')], default=0, verbose_name='Status'),
        ),
    ]
