# Generated by Django 5.0.2 on 2024-02-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xkom', '0003_alter_itemmodel_link_alter_itemmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='category',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nazwa'),
        ),
    ]
