# Generated by Django 5.0.2 on 2024-02-27 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xkom', '0007_remove_reportelement_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelement',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
