# Generated by Django 5.0.2 on 2024-02-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xkom', '0009_alter_reportelement_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportelement',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
