# Generated by Django 5.0.2 on 2024-02-27 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xkom', '0011_remove_reportelement_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportelement',
            name='created_datetime',
        ),
        migrations.AddField(
            model_name='reportelement',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
