# Generated by Django 5.0.2 on 2024-02-29 12:11

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xkom', '0013_alter_reportelement_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelement',
            name='creation_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reportelement',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
