# Generated by Django 5.0.2 on 2024-02-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xkom', '0017_alter_reportelement_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportelement',
            name='creation_time',
            field=models.TimeField(blank=True, default='13:19'),
        ),
    ]
