# Generated by Django 5.0.2 on 2024-02-29 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xkom', '0019_alter_reportelement_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportelement',
            name='creation_date',
            field=models.DateField(default=datetime.date(2024, 2, 29)),
        ),
        migrations.AlterField(
            model_name='reportelement',
            name='creation_time',
            field=models.TimeField(blank=True, default='13:20', null=True),
        ),
    ]
