# Generated by Django 5.0.2 on 2024-02-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xkom', '0020_alter_reportelement_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportelement',
            name='creation_time',
        ),
        migrations.AlterField(
            model_name='reportelement',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
    ]
