# Generated by Django 5.0.2 on 2024-03-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xkom', '0021_remove_reportelement_creation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelement',
            name='img',
            field=models.ImageField(default='images/default.jpg', upload_to='images/', verbose_name='Zdjęcie'),
        ),
    ]
