# Generated by Django 5.0.2 on 2024-03-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xkom', '0026_alter_reportelement_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelement',
            name='starting_price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cena Wyjściowa'),
        ),
    ]
