# Generated by Django 5.0.2 on 2024-03-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xkom', '0027_reportelement_starting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportelement',
            name='full_difference',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Pełna różnica'),
        ),
    ]
